<a href="https://colab.research.google.com/github/nikhilreddybilla28/acadacs/blob/main/nilpotentapp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###  ACS PROJECT



*Given a N * N matrix and the task is to check matrix is Nilpotent or not.*
   
   
Nilpotent Matrix: A square matrix  A  is called nilpotent matrix of order  k  provided it satisfies the relation,  A^k=O  and  A^k−1≠O,  where  k  is a positive integer &  O  is a null matrix of order  k  and  k  is the order of the nilpotent matrix  A .

The characteristic polynomial of any n×n matrix is of degree at most n, and the matrix is a root of that polynomial.

Since the minimal polynomial of a nilpotent must divide x^N for some N, and it also divides the characteristic polynomial, you have that the minimal polynomial is of the form x^k for some 0≤k≤n.So the index(k) of an n × n nilpotent matrix is always less than or equal to order of matrix(n).

    ***Algorithm***

    p=1

    while p < n:  #iter till order or matrix

        if A^p == O:
           return Nilpotent

        else:
           p=p+1

    return not a nilpotent matrix

In [1]:
import pandas as pd
import numpy as np
def check_nilpotent(a):
    n=int(len(a))
    O=np.zeros((n,n), dtype=int)
    m=np.array(a, dtype=int)
    R=np.array(m, dtype=int)
    k=1
    print(f'M :')
    print(R)
    #pd.DataFrame(R)
    if np.array_equal(R,O):
        return  'Nilpotent matrix with index: 1'
    else:
        while k<n:
            R = np.dot(R,m)
            print(f'M^{k+1} : ')
            print(R)
            if np.array_equal(R,O):
                return  f'Nilpotent matrix with index:{k+1}'
                #break
            k+=1
        if k==n:
            return 'Not a Nilpotent matrix'

In [4]:
# interface
import ipywidgets as widgets
from IPython.display import display

def classify_on_click(btn):
  txt
  print(txt.value)
  ar=[int(x) for x in txt.value.split()]
  n=int(len(ar)**0.5)
  M=np.reshape(ar,(n,n))
  pred = check_nilpotent(M)

  html = "<div align='center'>"
  html += "<h3> Matrix  is " + str(pred) + "</h3>"
  html += "</div>"
  htmlResult.value = html


htmlImage = widgets.HTML(value="")

txt = widgets.Text(
    placeholder='Enter NXN values ',
    description='Input:',
    disabled=False
)
'''txt
print(txt.value)
ar=[int(x) for x in txt.value.split()]
n=int(len(ar)**0.5)
M=np.reshape(ar,(n,n))'''

btnClassify = widgets.Button(description="Check")
btnClassify.on_click(classify_on_click)
boxH = widgets.HBox([txt , btnClassify])

htmlResult = widgets.HTML(value="<h3> check matrix is Nilpotent or not </h3>")
htmlResult.layout.margin = "0px 0px 40px 0px"

boxV = widgets.VBox([htmlImage, boxH, htmlResult])

boxV.layout.align_items = "center"
display(boxV)

0 2 1 6 0 0 1 2  0 0 0 3 0 0 0 0
M :
[[0 2 1 6]
 [0 0 1 2]
 [0 0 0 3]
 [0 0 0 0]]
M^2 : 
[[0 0 2 7]
 [0 0 0 3]
 [0 0 0 0]
 [0 0 0 0]]
M^3 : 
[[0 0 0 6]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
M^4 : 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]



 For example, the matrix B,

B=\begin{bmatrix} 
0 & 2 & 1 & 6\\
0 & 0 & 1 & 2\\
0 & 0 & 0 & 3\\
0 & 0 & 0 & 0 
\end{bmatrix}

B^2=\begin{bmatrix} 
0 & 0 & 2 & 7\\
0 & 0 & 0 & 3\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 
\end{bmatrix}

B^3=\begin{bmatrix} 
0 & 0 & 0 & 6\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 
\end{bmatrix}

 
B^4=\begin{bmatrix} 
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 
\end{bmatrix}


The index of <math>B</math> is therefore 4


     

    118EE0326
    Nikhil Reddy